
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Dec 07 18:07:16 CST 2013
//----------------------------------------------------

package DynasT.Analysis.Classes;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTERESTS = 31;
  public static final int OUTLAY = 25;
  public static final int OPCURLYBRAC = 8;
  public static final int REVENUE = 30;
  public static final int EQUALS = 14;
  public static final int GROSS = 44;
  public static final int COSTS = 19;
  public static final int FLOW = 23;
  public static final int MINUS = 5;
  public static final int INFO = 26;
  public static final int UPPER_MIN = 36;
  public static final int POLKADOT = 7;
  public static final int YES = 42;
  public static final int SEMICOLON = 13;
  public static final int FRENCH = 24;
  public static final int FIRST = 27;
  public static final int INF = 28;
  public static final int COMMA = 10;
  public static final int PROGNOSTIC = 33;
  public static final int PLUS = 4;
  public static final int CLBRAC = 3;
  public static final int GERMAN = 17;
  public static final int MARR = 37;
  public static final int SCENARIO = 22;
  public static final int EOF = 0;
  public static final int INFMIN = 29;
  public static final int error = 1;
  public static final int DEPRECIATE = 38;
  public static final int NET = 45;
  public static final int OPBRAC = 2;
  public static final int NUMBER = 39;
  public static final int START = 21;
  public static final int ASSETS = 15;
  public static final int PATENT = 32;
  public static final int TIMES = 6;
  public static final int LAST = 16;
  public static final int NO = 43;
  public static final int OPSQBRAC = 11;
  public static final int TREE = 18;
  public static final int CLSQBRAC = 12;
  public static final int PERCENTAGE = 41;
  public static final int OPTIMIZER = 34;
  public static final int UPPER = 35;
  public static final int TIERED = 20;
  public static final int CLCURLYBRAC = 9;
  public static final int IDENTIFIER = 40;
}

