
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 09 11:29:47 CST 2013
//----------------------------------------------------

package DynasT.Analysis.Classes;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINIMUM = 35;
  public static final int OUTLAY = 26;
  public static final int OPCURLYBRAC = 10;
  public static final int REVENUE = 31;
  public static final int EQUALS = 16;
  public static final int GROSS = 45;
  public static final int COSTS = 20;
  public static final int FLOW = 24;
  public static final int MINUS = 6;
  public static final int INFO = 27;
  public static final int UPPER_MIN = 37;
  public static final int POLKADOT = 9;
  public static final int YES = 43;
  public static final int SEMICOLON = 15;
  public static final int FRENCH = 25;
  public static final int FIRST = 28;
  public static final int INF = 29;
  public static final int COMMA = 12;
  public static final int PROGNOSTIC = 33;
  public static final int PLUS = 5;
  public static final int CLBRAC = 3;
  public static final int GERMAN = 19;
  public static final int MARR = 38;
  public static final int SCENARIO = 23;
  public static final int EOF = 0;
  public static final int INFMIN = 30;
  public static final int error = 1;
  public static final int DEPRECIATE = 39;
  public static final int NET = 46;
  public static final int OPBRAC = 2;
  public static final int NUMBER = 40;
  public static final int START = 22;
  public static final int ASSETS = 17;
  public static final int PATENT = 32;
  public static final int TIMES = 7;
  public static final int LAST = 18;
  public static final int NO = 44;
  public static final int OPSQBRAC = 13;
  public static final int CLSQBRAC = 14;
  public static final int PERCENTAGE = 42;
  public static final int OPTIMIZER = 34;
  public static final int POINTER = 8;
  public static final int AVERAGE = 4;
  public static final int UPPER = 36;
  public static final int TIERED = 21;
  public static final int CLCURLYBRAC = 11;
  public static final int IDENTIFIER = 41;
}

