
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 06 23:51:08 CST 2013
//----------------------------------------------------

package DynasT.Analysis.Classes;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTERESTS = 34;
  public static final int DIVIDE = 7;
  public static final int OUTLAY = 28;
  public static final int OPCURLYBRAC = 9;
  public static final int REVENUE = 33;
  public static final int EQUALS = 15;
  public static final int GROSS = 46;
  public static final int COSTS = 21;
  public static final int FLOW = 26;
  public static final int MINUS = 5;
  public static final int INFO = 29;
  public static final int UPPER_MIN = 39;
  public static final int POLKADOT = 8;
  public static final int YES = 44;
  public static final int SEMICOLON = 14;
  public static final int FRENCH = 27;
  public static final int FIRST = 30;
  public static final int INF = 31;
  public static final int PROGNOSTIC = 36;
  public static final int COMMA = 11;
  public static final int PLUS = 4;
  public static final int CLBRAC = 3;
  public static final int GERMAN = 19;
  public static final int MARR = 40;
  public static final int SCENARIO = 24;
  public static final int EOF = 0;
  public static final int INFMIN = 32;
  public static final int error = 1;
  public static final int NET = 47;
  public static final int OPBRAC = 2;
  public static final int NUMBER = 41;
  public static final int START = 23;
  public static final int ASSETS = 17;
  public static final int PATENT = 35;
  public static final int TIMES = 6;
  public static final int LAST = 18;
  public static final int NO = 45;
  public static final int OPSQBRAC = 12;
  public static final int TREE = 20;
  public static final int CLSQBRAC = 13;
  public static final int END = 25;
  public static final int PERCENTAGE = 43;
  public static final int OPTIMIZER = 37;
  public static final int POINTER = 16;
  public static final int UPPER = 38;
  public static final int TIERED = 22;
  public static final int CLCURLYBRAC = 10;
  public static final int IDENTIFIER = 42;
}

