/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package finansyx;

import finansyx.commons.FlujoDeCaja.*;
import finansyx.commons.FlujoDeCaja.Rules.*;
import finansyx.commons.modelos.ModeloFlujo;
/**
 *
 * @author t4r0
 */
public class CashFlow extends javax.swing.JPanel {

    FlujoDeCaja flujo = new FlujoDeCaja();
            
            
    /**
     * Creates new form CashFlow
     */
    public CashFlow() {
        initComponents();
        flujo.setIngresos(new Ingresos("Ingresos", new StaticCalcRule(300.)));
        flujo.setCostos(new Gastos("Costos", new StaticCalcRule(200.)));
        flujo.setUAI(new Gastos("UAI", new StaticCalcRule(100.)));
        flujo.setUBruta(new Gastos("UBRUTA", new StaticCalcRule(20.)));
        tblCashFlow.setModel(new ModeloFlujo(flujo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCashFlow = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout(1, 0));

        tblCashFlow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCashFlow);

        add(jScrollPane1, java.awt.BorderLayout.LINE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCashFlow;
    // End of variables declaration//GEN-END:variables
}
